[package]
name = "m6502"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.8.0"
env_logger = "0.11.6"
log = "0.4.25"
smart-default = "0.7.1"
